/**
 * Se inicializa en git
 */
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanasAlmacen;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.WindowConstants;

/**
 *
 * @author pablo.castaño
 */
public class Inicio extends javax.swing.JFrame {

   
    public Inicio() {
        initComponents();
        setSize(600, 400);
        setResizable(false);
        setTitle("Menu Principal Almacen");
        setLocationRelativeTo(null);
        
        ImageIcon wallpaper = new ImageIcon("src/imagenes/wallpaperPrincipal.jpg");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(jLabel_Wallpaper.getWidth(),
                jLabel_Wallpaper.getHeight(), Image.SCALE_DEFAULT));
        jLabel_Wallpaper.setIcon(icono);
        this.repaint();
    }
    
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/Logo_Negro.jpg"));
        return retValue;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_RegCliente = new javax.swing.JButton();
        jButton_RegProducto = new javax.swing.JButton();
        jButton_Ventas = new javax.swing.JButton();
        jLabel_Titulo = new javax.swing.JLabel();
        jLabel_RegCliente = new javax.swing.JLabel();
        jLabel_RegProducto = new javax.swing.JLabel();
        jLabel_RegVentas = new javax.swing.JLabel();
        jLabel_Wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton_RegCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/addUser.png"))); // NOI18N
        jButton_RegCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RegClienteActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_RegCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 120, 100));

        jButton_RegProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/apoyo-tecnico.png"))); // NOI18N
        jButton_RegProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RegProductoActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_RegProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 120, 100));

        jButton_Ventas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/editar.png"))); // NOI18N
        jButton_Ventas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_VentasActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Ventas, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, 120, 100));

        jLabel_Titulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel_Titulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Titulo.setText("Supermercado UQ");
        getContentPane().add(jLabel_Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, -1, -1));

        jLabel_RegCliente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_RegCliente.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_RegCliente.setText("Registrar Cliente");
        getContentPane().add(jLabel_RegCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        jLabel_RegProducto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_RegProducto.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_RegProducto.setText("Registrar Producto");
        getContentPane().add(jLabel_RegProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, -1, -1));

        jLabel_RegVentas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_RegVentas.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_RegVentas.setText("Registrar Ventas");
        getContentPane().add(jLabel_RegVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 240, -1, -1));
        getContentPane().add(jLabel_Wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_VentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_VentasActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        RegVenta venta = new RegVenta();
        venta.setVisible(true);
    }//GEN-LAST:event_jButton_VentasActionPerformed

    private void jButton_RegClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RegClienteActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        RegCliente cliente = new RegCliente();
        cliente.setVisible(true);
        
    }//GEN-LAST:event_jButton_RegClienteActionPerformed

    private void jButton_RegProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RegProductoActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        RegProducto_1 producto = new RegProducto_1();
        producto.setVisible(true);
    }//GEN-LAST:event_jButton_RegProductoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_RegCliente;
    private javax.swing.JButton jButton_RegProducto;
    private javax.swing.JButton jButton_Ventas;
    private javax.swing.JLabel jLabel_RegCliente;
    private javax.swing.JLabel jLabel_RegProducto;
    private javax.swing.JLabel jLabel_RegVentas;
    private javax.swing.JLabel jLabel_Titulo;
    private javax.swing.JLabel jLabel_Wallpaper;
    // End of variables declaration//GEN-END:variables
}
