/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanasAlmacen;

import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JTable;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pablo.castaño
 */
public class RegVenta extends javax.swing.JFrame {

    DefaultTableModel model = new DefaultTableModel();
    public RegVenta() {
        initComponents();
        setTitle("Registrar nuevo producto");
        setSize(1050, 720);
        setResizable(false);
        setLocationRelativeTo(null);


        ImageIcon wallpaper = new ImageIcon("src/imagenes/wallpaperPrincipal.jpg");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(jLabel_Wallpaper.getWidth(),
                jLabel_Wallpaper.getHeight(), Image.SCALE_DEFAULT));
        jLabel_Wallpaper.setIcon(icono);
        this.repaint();
        
        jTable_Venta = new JTable(model);
        jScrollPane1.setViewportView(jTable_Venta);

        model.addColumn("Codigo de transacción");
        model.addColumn("Fecha");
        model.addColumn("Cliente");
        model.addColumn("Producto");
        model.addColumn("Cantidad de producto");
        model.addColumn("Subtotal");
        model.addColumn("Iva");
        model.addColumn("Total");
        
        jTable_Venta.addMouseListener(new MouseAdapter(){
            @Override
            public void mouseClicked(MouseEvent e){
                int fila_point = jTable_Venta.rowAtPoint(e.getPoint());
                int columna_point = 0;
                
                if(fila_point > -1){
                    
                    int selectedRow = jTable_Venta.getSelectedRow();
                if (selectedRow != -1) {
                    for (int column = 0; column < jTable_Venta.getColumnCount(); column++) {
                        Object value = jTable_Venta.getValueAt(selectedRow, column);
                        System.out.println("Valor en fila " + selectedRow + ", columna " + column + ": " + value);
                        
                        if(column == 0){
                            jTextField_CodigoTransaccion.setText((String) value);                            
                        }
                        if(column == 1){
                            jTextField_FechaVenta.setText((String) value);                            
                        }
                        
                        if(column == 2){
                            jTextField_Cliente.setText((String) value);                            
                        }
                        
                        if(column == 3){
                            jTextField_Producto.setText((String) value);                            
                        }
                        
                        if(column == 4){
                            jTextField_CantidadVendida.setText((String) value);                            
                        }
                        
                        if(column == 5){
                            jTextField_Subtotal.setText((String) value);                            
                        }
                        
                        if(column == 6){
                            jTextField_Iva.setText((String) value);                            
                        }
                        
                        if(column == 7 ){
                            jTextField_Total.setText((String) value);                            
                        }
                        
  
                    }
                }
                   
                    
                    
                            
                }
            }
                        
        });
        
        
           
    }
    
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/Logo_Negro.jpg"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Venta = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jTextField_CodigoTransaccion = new javax.swing.JTextField();
        jTextField_FechaVenta = new javax.swing.JTextField();
        jTextField_Iva = new javax.swing.JTextField();
        jTextField_Total = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel_Cliente = new javax.swing.JLabel();
        jLabel_Iva = new javax.swing.JLabel();
        jLabel_Total = new javax.swing.JLabel();
        jButton_Registrar = new javax.swing.JButton();
        jButton_Actualizar = new javax.swing.JButton();
        jButton_Eliminar = new javax.swing.JButton();
        jPanel_DetalleVenta = new javax.swing.JPanel();
        jTextField_CantidadVendida = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField_Subtotal = new javax.swing.JTextField();
        jTextField_Producto = new javax.swing.JTextField();
        jLabel_DetalleVenta = new javax.swing.JLabel();
        jTextField_Cliente = new javax.swing.JTextField();
        jButton_Salir = new javax.swing.JButton();
        jLabel_Wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registro de ventas");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, -1, 30));

        jTable_Venta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable_Venta);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 990, 190));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTextField_CodigoTransaccion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField_CodigoTransaccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_CodigoTransaccionActionPerformed(evt);
            }
        });

        jTextField_FechaVenta.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField_FechaVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_FechaVentaActionPerformed(evt);
            }
        });

        jTextField_Iva.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField_Iva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_IvaActionPerformed(evt);
            }
        });

        jTextField_Total.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setText("Código de transacción:");

        jLabel4.setText("Fecha:");

        jLabel_Cliente.setText("Cliente:");

        jLabel_Iva.setText("Iva:");

        jLabel_Total.setText("Total:");

        jButton_Registrar.setText("Registrar");
        jButton_Registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RegistrarActionPerformed(evt);
            }
        });

        jButton_Actualizar.setText("Actualizar");
        jButton_Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ActualizarActionPerformed(evt);
            }
        });

        jButton_Eliminar.setText("Eliminar");
        jButton_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EliminarActionPerformed(evt);
            }
        });

        jPanel_DetalleVenta.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTextField_CantidadVendida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_CantidadVendidaActionPerformed(evt);
            }
        });

        jLabel2.setText("Cantidad de productos vendidos:");

        jLabel8.setText("Producto vendido:");

        jLabel9.setText("Subtotal:");

        javax.swing.GroupLayout jPanel_DetalleVentaLayout = new javax.swing.GroupLayout(jPanel_DetalleVenta);
        jPanel_DetalleVenta.setLayout(jPanel_DetalleVentaLayout);
        jPanel_DetalleVentaLayout.setHorizontalGroup(
            jPanel_DetalleVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_DetalleVentaLayout.createSequentialGroup()
                .addGroup(jPanel_DetalleVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_DetalleVentaLayout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(jLabel9))
                    .addGroup(jPanel_DetalleVentaLayout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(jLabel8))
                    .addGroup(jPanel_DetalleVentaLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addGroup(jPanel_DetalleVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField_Subtotal)
                            .addComponent(jTextField_CantidadVendida, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                            .addComponent(jTextField_Producto))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_DetalleVentaLayout.createSequentialGroup()
                .addGap(0, 171, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(165, 165, 165))
        );
        jPanel_DetalleVentaLayout.setVerticalGroup(
            jPanel_DetalleVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_DetalleVentaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jTextField_Producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jTextField_CantidadVendida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jTextField_Subtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jLabel_DetalleVenta.setText("Detalle de la venta:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4)
                                    .addComponent(jTextField_FechaVenta, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                                    .addComponent(jLabel_Cliente)
                                    .addComponent(jTextField_Cliente))
                                .addComponent(jTextField_CodigoTransaccion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel_Total)
                            .addComponent(jLabel_Iva)
                            .addComponent(jTextField_Iva, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                            .addComponent(jTextField_Total))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton_Registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jButton_Actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jButton_Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(104, 104, 104))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_DetalleVenta)
                            .addComponent(jPanel_DetalleVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel_DetalleVenta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextField_CodigoTransaccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_FechaVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel_Cliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(jLabel_Iva)
                        .addGap(10, 10, 10)
                        .addComponent(jTextField_Iva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel_Total)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField_Total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel_DetalleVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 990, 400));

        jButton_Salir.setText("Salir");
        jButton_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 640, 90, 40));
        getContentPane().add(jLabel_Wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_CodigoTransaccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_CodigoTransaccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_CodigoTransaccionActionPerformed

    private void jButton_RegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RegistrarActionPerformed
        
        
        String codigoTransaccion, fechaVenta, iva, subtotal, total, cantidadVendida, cliente, producto;

        codigoTransaccion = jTextField_CodigoTransaccion.getText().trim();
        fechaVenta = jTextField_FechaVenta.getText().trim();
        iva = jTextField_Iva.getText().trim();
        subtotal = jTextField_Subtotal.getText().trim();
        total = jTextField_Total.getText().trim();
        cantidadVendida = jTextField_CantidadVendida.getText().trim();
        cliente = jTextField_Cliente.getText().trim();
        producto = jTextField_Producto.getText().trim();
        
        

        Object[] fila = new Object[8];

            fila[0] = codigoTransaccion;
            fila[1] = fechaVenta;
            fila[2] = cliente;
            fila[3] = producto;
            fila[4] = cantidadVendida;
            fila[5] = subtotal;
            fila[6] = iva;
            fila[7] = total;
        
        model.addRow(fila);
       
        Limpiar();
    }//GEN-LAST:event_jButton_RegistrarActionPerformed

    private void jTextField_IvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_IvaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_IvaActionPerformed

    private void jTextField_FechaVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_FechaVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_FechaVentaActionPerformed

    private void jTextField_CantidadVendidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_CantidadVendidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_CantidadVendidaActionPerformed

    private void jButton_ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ActualizarActionPerformed
      
        int selectedRow = jTable_Venta.getSelectedRow(); 
    if (selectedRow >= 0) {
        
        String codigoTransaccion, fechaVenta, iva, subtotal, total, cantidadVendida, cliente, producto;

        codigoTransaccion = jTextField_CodigoTransaccion.getText().trim();
        fechaVenta = jTextField_FechaVenta.getText().trim();
        iva = jTextField_Iva.getText().trim();
        subtotal = jTextField_Subtotal.getText().trim();
        total = jTextField_Total.getText().trim();
        cantidadVendida = jTextField_CantidadVendida.getText().trim();
        cliente = jTextField_Cliente.getText().trim();
        producto = jTextField_Producto.getText().trim();

        // Actualizar los datos en la fila seleccionada
        model.setValueAt(codigoTransaccion, selectedRow, 0);
        model.setValueAt(fechaVenta, selectedRow, 1);
        model.setValueAt(cliente, selectedRow, 2);
        model.setValueAt(producto, selectedRow, 3);
        model.setValueAt(cantidadVendida, selectedRow, 4);
        model.setValueAt(subtotal, selectedRow, 5);
        model.setValueAt(iva, selectedRow, 6);
        model.setValueAt(total, selectedRow, 7);
        
    }
        
        Limpiar();
    }//GEN-LAST:event_jButton_ActualizarActionPerformed

    private void jButton_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EliminarActionPerformed
        int selectedRow = jTable_Venta.getSelectedRow(); // Supongamos que jTable es el nombre de tu tabla
    if (selectedRow >= 0) {
        model.removeRow(selectedRow);
        
    }
    Limpiar();
    }//GEN-LAST:event_jButton_EliminarActionPerformed

    private void jButton_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SalirActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Inicio inicio = new Inicio();
        inicio.setVisible(true);
    }//GEN-LAST:event_jButton_SalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegVenta().setVisible(true);
            }
        });
    }
    
    public void Limpiar(){
    
    jTextField_CodigoTransaccion.setText("");
    jTextField_FechaVenta.setText("");
    jTextField_CantidadVendida.setText("");
    jTextField_Subtotal.setText("");
    jTextField_Iva.setText("");
    jTextField_Total.setText("");
    
    
    
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Actualizar;
    private javax.swing.JButton jButton_Eliminar;
    private javax.swing.JButton jButton_Registrar;
    private javax.swing.JButton jButton_Salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_Cliente;
    private javax.swing.JLabel jLabel_DetalleVenta;
    private javax.swing.JLabel jLabel_Iva;
    private javax.swing.JLabel jLabel_Total;
    private javax.swing.JLabel jLabel_Wallpaper;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel_DetalleVenta;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Venta;
    private javax.swing.JTextField jTextField_CantidadVendida;
    private javax.swing.JTextField jTextField_Cliente;
    private javax.swing.JTextField jTextField_CodigoTransaccion;
    private javax.swing.JTextField jTextField_FechaVenta;
    private javax.swing.JTextField jTextField_Iva;
    private javax.swing.JTextField jTextField_Producto;
    private javax.swing.JTextField jTextField_Subtotal;
    private javax.swing.JTextField jTextField_Total;
    // End of variables declaration//GEN-END:variables
}
